# name of pipeline workflow
name: Shobhit terraform workflow 
# trigger action 
# when there is a push happen in master branch pipeline gonna trigger
on: 
  push:
    branches: [ "main" ]  
    paths-ignore:
      - "README.md"

# creating jobs 
jobs:
  test-job:
    runs-on: ubuntu-latest 
    steps: # what exactly you want to run in ubuntu machine 
    # calling first github action to clone my dryrun-aws data to runner machine 
    - name: taking code from my repo 
      uses: actions/checkout@v5
      with:
        ref: main 
# terrafor installing 
    - name: installing terraform 
      uses: hashicorp/setup-terraform@v3
# running some commands 
    - name: my first step to test github action 
      run: |
        echo "Hello world"
        git version 
        whoami
        ls -a 
        terraform version
      # Configure AWS Secret Keys
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: ap-southeast-2

    - name: Verify AWS Connection
      run: |
        echo "checking with command"
        aws s3 ls
